github.com:
    users:
        pham-noah:
            oauth_token: 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
    git_protocol: https
    user: pham-noah
    oauth_token: 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
