github.com:
    users:
        pham-noah:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: pham-noah
